version: '3'
services:
  database:
    image: postgres:alpine
    restart: always
    volumes:
      - /volume1/docker/Nextcloud/postgres-nextcloud:/var/lib/postgresql/data
    env_file:
      - database.env
  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - 3000:80
    volumes:
      - /volume1/docker/Nextcloud/main-nextcloud:/var/www/html
      - /volume1/docker/Nextcloud/apps-nextcloud:/var/www/html/custom_apps
      - /volume1/docker/Nextcloud/config-nextcloud:/var/www/html/config
      - /volume1/docker/Nextcloud/data-nextcloud:/var/www/html/data
      - /volume1/docker/Nextcloud/theme-nextcloud:/var/www/html/themes
      - /volume1/Testing/:/testing
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: nextcloud
    env_file:
      - database.env
    depends_on:
      - database