version: '3'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
    restart: always
    volumes:
      - /volume1/docker/postgres-nextcloud:/var/lib/postgresql/data
  archivesspace:
    image: nextcloud:latest
    ports:
      - 8090:80
    depends_on:
      - database
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
    links:
      - database
    volumes:
      - /volume1/docker/main-nextcloud:/var/www/html
      - /volume1/docker/apps-nextcloud:/var/www/html/custom_apps
      - /volume1/docker/config-nextcloud:/var/www/html/config
      - /volume1/docker/data-nextcloud:/var/www/html/data
      - /volume1/docker/theme-nextcloud:/var/www/html/themes
      - /volume1/docker/testing:/testing

